name: Update .chatpin on commit

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update .chatpin with latest commit SHA
        run: |
          echo ${{ github.sha }} > .chatpin

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update .chatpin to latest commit"
          file_pattern: .chatpin
